project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto 

website:
  title: "grace v. ringlein"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true


