---
title: "bash_part4"
editor: visual
---
Use wget to download four files that end in .fastq from here.
Create a directory to download the data. The top level directory should be called raw_data and there should be a sub-level directory called fastq. The command you write should force the creation of both directories at the same time if either of them do not exist yet.
Move all the .fastq files into the fastq sub-level directory.
List all the .fastq files that end in a 12 or 13.
Search for the string NNNN in the SRR1039512_subset_1.fastq file. In addition to returning the matched line in the .fastq file, your output should also return the two lines before and the four lines after the matching line.
Write a for loop in the shell that iterates over each .fastq file. For each .fastq file, do the following. In the first 1000 rows for each file, count the number of lines where the “@” symbol appears. Your final output should be four numbers printed to the screen.

Use wget to download four files that end in .fastq from here.
```{bash}
wget https://raw.githubusercontent.com/stephaniehicks/jhustatprogramming2023/main/data/SRR1039508_subset_1.fastq
 
wget https://raw.githubusercontent.com/stephaniehicks/jhustatprogramming2023/main/data/SRR1039512_subset_1.fastq
  
wget https://raw.githubusercontent.com/stephaniehicks/jhustatprogramming2023/main/data/SRR1039509_subset_1.fastq
   
wget https://raw.githubusercontent.com/stephaniehicks/jhustatprogramming2023/main/data/SRR1039513_subset_1.fastq
```
Create a directory to download the data. The top level directory should be called raw_data and there should be a sub-level directory called fastq. The command you write should force the creation of both directories at the same time if either of them do not exist yet.

```{bash}
mkdir -p raw_data/fastq
```

Move all the .fastq files into the fastq sub-level directory.
```{bash}
mv *.fastq raw_data/fastq/.
```

List all the .fastq files that end in a 12 or 13.
```{bash}
ls raw_data/fastq/SRR103951*_subset_1.fastq 
```

```{bash}
line_num=$(grep -n NNNN raw_data/fastq/SRR1039512_subset_1.fastq | cut  -d : -f 1)
echo $line_num
end_line=$(($line_num + 4))
head -n $end_line raw_data/fastq/SRR1039512_subset_1.fastq | tail -n 7
```

```{bash}
for file in raw_data/fastq/*.fastq
do 
  head -n 1000 $file | grep "@"  | wc -l
done
```

